// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gTmjIXRQJ_cyZF9-fG5SdDWy_Uh1S2Y',
    appId: '1:503700376156:web:52b71c55a1a5fb9905b499',
    messagingSenderId: '503700376156',
    projectId: 'tik--took-clone',
    authDomain: 'tik--took-clone.firebaseapp.com',
    storageBucket: 'tik--took-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7YoATugkGl3s0VG_OSc5XUFH6vdFzOCk',
    appId: '1:503700376156:android:609674336b868b7a05b499',
    messagingSenderId: '503700376156',
    projectId: 'tik--took-clone',
    storageBucket: 'tik--took-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaRbAajGQYhrJli0_L4R6yJoNGMMHEbuY',
    appId: '1:503700376156:ios:cf5e37afc77fdc5d05b499',
    messagingSenderId: '503700376156',
    projectId: 'tik--took-clone',
    storageBucket: 'tik--took-clone.appspot.com',
    iosClientId: '503700376156-i0thou6ulrn57bg6u1qn4du04e0alf1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaRbAajGQYhrJli0_L4R6yJoNGMMHEbuY',
    appId: '1:503700376156:ios:cf5e37afc77fdc5d05b499',
    messagingSenderId: '503700376156',
    projectId: 'tik--took-clone',
    storageBucket: 'tik--took-clone.appspot.com',
    iosClientId: '503700376156-i0thou6ulrn57bg6u1qn4du04e0alf1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokclone',
  );
}
